# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ale.earth
goodbye: Thanks, visit again soon!<br/>More projects are on the way.
description: > # this means to ignore newlines until "baseurl:"
  This website is home to Alejandro Machado's projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.ale.earth"
enforce_ssl: "www.ale.earth"

# Build settings
markdown: kramdown

# Custom settings
permalink: /:categories/:title
timezone: America/Caracas
